server:
  port: 8081

spring:
  profiles:
    default: dev
  application:
    name: integration-admin-api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  autoconfigure:
    exclude:
      - org.springframework.boot.actuate.autoconfigure.tracing.zipkin.ZipkinAutoConfiguration

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  tracing:
    sampling:
      probability: 1.0

integration:
  security:
    enabled: true
  openapi:
    title: Integration Admin API
    version: 1.0.0
  admin:
    security:
      redis-token-blacklist-enabled: true
  encrypt:
    enable: true
    decrypt-request-body-enabled: true
    encrypt-response-body-enabled: false
    aes-key-size: 256
    rsa-transformation: RSA/ECB/OAEPWithSHA-256AndMGF1Padding
    exclude-paths:
      - "/actuator"
      - "/actuator/**"
      - "/api/admin/auth/login"
      - "/api/admin/auth/logout"
      - "/api/admin/open"
      - "/doc.html"
      - "/swagger-ui"
      - "/swagger-ui/**"
      - "/swagger-ui.html"
      - "/v3/api-docs"
      - "/v3/api-docs/**"
      - "/webjars/**"

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} [%X{traceId:-}] %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
