server:
  port: 8084

spring:
  application:
    name: integration-mq-consumer
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  autoconfigure:
    exclude:
      - org.springframework.boot.actuate.autoconfigure.tracing.zipkin.ZipkinAutoConfiguration

management:
  endpoints:
    web:
      exposure:
        include: health,info
  tracing:
    sampling:
      probability: 1.0

integration:
  openapi:
    enabled: false
  mq:
    consumer:
      enabled: true
      queue: integration.job.tasks
      exchange: integration.job.exchange
      routing-key: integration.job.task

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} [%X{traceId:-}] %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
