server:
  port: 8087

spring:
  application:
    name: integration-encrypt-demo

management:
  endpoints:
    web:
      exposure:
        include: health,info

# 演示用 RSA 2048 密钥对（勿用于生产）；算法与 starter 默认 OAEP 一致
integration:
  encrypt:
    enable: true
    rsa-public-key: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtKkCzegaCV89aeLLIqoF1Q+RfpKnR1w7gguj4E8No4X+eGvBEyHdWp9fAH6Lbf6HyKWKiW+6rYlCV42xdc5CInyJ6Yz68i0d46yNyrrG5AVZm8d3/rPyA0DTBfwdP1mE/DQSIbVU4oXybbPdCh3uF69go9Q0oXgE1THur0VUSVMlQJbJ5/Qll+aJw1VNe7tW5pIksEfsZTHfPe8m9VX8u4yqfJdRWp9+XW3S4h+aUFwQ+sCjKQUyWSQelh4trVO3VhGyACPfOoCu9PfPRhaL05oQ9IYibCyPZsddMqsrohDKBRkaQ5v32HwX5d9gmAud3R2dJF65Jm1PaS/SFHq93wIDAQAB"
    rsa-private-key: "MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC0qQLN6BoJXz1p4ssiqgXVD5F+kqdHXDuCC6PgTw2jhf54a8ETId1an18Afott/ofIpYqJb7qtiUJXjbF1zkIifInpjPryLR3jrI3KusbkBVmbx3f+s/IDQNMF/B0/WYT8NBIhtVTihfJts90KHe4Xr2Cj1DSheATVMe6vRVRJUyVAlsnn9CWX5onDVU17u1bmkiSwR+xlMd897yb1Vfy7jKp8l1Fan35dbdLiH5pQXBD6wKMpBTJZJB6WHi2tU7dWEbIAI986gK70989GFovTmhD0hiJsLI9mx10yqyuiEMoFGRpDm/fYfBfl32CYC53dHZ0kXrkmbU9pL9IUer3fAgMBAAECggEAFHtMzBdSTFm11rlVmlp4Ss13C0iJGngEbxvuulF8FFvum6xruUWPmOSUmrO+DvxaXI8YA7jdCyuSj+aKhfaaXNqNsCLBmI8w4kz/zkoanmNU42pb2k6AU4oX4ofQsQvvHcCxhYzPUNcqwvEvUCRQh/LkG+7FAMFgmuMMUmajxaQsw0e0hh1wEg0ASwmUmPFMmVUnz2Tttq5+oPi5z5W5nhv8ioT8HHqAwtBgXOFGYuK23fe6R8ByVZO1jzV0C8pe0DmoqPdePHwMN/oSfGxkYPo/aBqwhAFZOovzvexIFR2uRiGniEdnp0jZ8CrUHCFmTiH0drCb42zSHydJoKVqsQKBgQDY0YOUWFVtE65Ud1NycUZkW2tMV3Dc1YDwz43cPTuvLHIn5aocEKGBt6N0RCIh9OKyOwUb9QjHYFvPrL4u9kXNBZMfsXiPWqqQNHoT41MYUs7RXwy9nyEYYEtzVqu4Po3p2KtlWbpvXaHjgEu/sj+80+hPbTLKJg6CtEoj1SgA0wKBgQDVTr19/c7h4Ueh1BvHPuaYdOb+x58jAd4XUCafZgwQ7I8VR/jmrnEGCvrXcRLJ30K7r0++n9+t84s3CYVeqeDT1E16KtXJtkYkrWSiAoj87lbHDGjD32ElcJCB8pl2yTr0cIOQDJRJnEGYoB+kyt6bhaaAetasFr3Xhr96SqhHRQKBgFBG2ontXsvBErXRbIMd76susf6VDYOmRVRj9KlLvrJwKWAeR6qWecX2gT2GEIE0E09cTNr6EaMISVYOJmhq5JMxcjS01+dz8VztIRoF+/kwh8S7hZMbvPwygx0URQY1mwOvJl6jJ0UejNcX5HP4gmLers/hpYF1L8AzEpRL0sDjAoGAKrjYjxF0jB0Ywbq/zYo1mTdgxIqqvtIy7yxob+h6ZjFa/wIpQdqSXIl6cAf/oVsL/JdCO4W9wRNUQLOxeKJBm2ucEOnfY8UUC2iHDUPAuBfsXXWIziJBTMRczQoP3pCzNB4M258JXCzlnnIDpHfVWgTMslLoCBON9krQsuedCJkCgYACNBKrk9r2u58YC/PhxXUrF9gzgGp4UtO5qDdgAEpuNaw++mexqbxiSrWaNNP88Plrb4LC61RSXnynpPUozC77lRxGn7L9ZdIG9rMbluUz8lgIcrG60dFXTU8fPLKwoFsmwEfj1CzDH872nHEC241je2K+35kYOpNL2OwE4rUGUg=="
